### ISSUE TITLE
Conditional steps not working

### ISSUE THREAD

**Issue by futtetennista** [buildkite/cli#144]
Given the following pipeline

```yaml
steps:
  - command: echo 'I should not be executed'
    if: false
```
the step isn't ignored when running `bk local run`. Same with other false conditions e.g. `if: 1 == 0`.

Tested using version `2.0.0`.
