### ISSUE TITLE
Groups not supported in Buildkite CLI

### ISSUE THREAD

**Issue by jbugeja-wesdigital** [buildkite/cli#147]
I am trying to run a pipeline locally with `bk local run` when the pipeline reaches my group step it fails with the message:

`🚨 Error: The command phase has no 'command' to execute. Provide a 'command' field in your step configuration, or define a 'command' hook in a step plug-in, your repository '.buildkite/hooks', or agent 'hooks-path'.`

This is the pipeline I tested with:

```
steps:
  - label: "test0"
    command: echo test0
  - group: "grouptest" 
    steps:
      - label: "test1"
        command: echo test1
      - label: "test2"
        command: echo test2
```

If I add a command under group it will pass, although it ignores any steps under my group, for example:

```
steps:
  - label: "test0"
    command: echo test0
  - group: "grouptest" 
    command: echo group
    steps:
      - label: "test1"
        command: echo test1
      - label: "test2"
        command: echo test2
```

This will print out only test0 and group. Are groups going to be supported via Buildkite CLI soon?
