### ISSUE TITLE
bk run supports docker plugin, but is not propagating env vars

### ISSUE THREAD

**Issue by drnic** [buildkite/cli#77]
Consider this pipeline:

https://gist.github.com/drnic/a042bd719ed9213c5af7fd1605f8bf93#file-pipeline-bk-run-docker-fail-yml

When you run it, the `-E AGENT_ENV=foobar` value is not propagated into Docker:

```
git clone https://gist.github.com/drnic/a042bd719ed9213c5af7fd1605f8bf93 ~/workspace/pipeline.bk-run-docker-fail
cd ~/workspace/pipeline.bk-run-docker-fail

bk run pipeline.bk-run-docker-fail.yml -E AGENT_ENV=where-is-this-env
```

The output should include the two lines:

```
STEP_ENV=found-step-env
AGENT_ENV=where-is-this-env
```

But it only includes the first one:

```
STEP_ENV=found-step-env
```

Why does `bk local run -E AGENT_ENV=xyz` not pass `$AGENT_ENV` into the docker plugin env?

**Comment by drnic** [comment]
Resolved on slack. Need to use `environments:` to explicitly declare vars coming from outside pipeline.

```
steps:
  - label: ":docker:"
    env:
      STEP_ENV: found-step-env
    commands:
      - env | grep STEP_ENV
      - env | grep AGENT_ENV
    plugins:
      - docker#v3.5.0:
          image: "alpine:latest"
          environments:
          - STEP_ENV
          - AGENT_ENV
```
