### ISSUE TITLE
some emoji missing or different set supported?

### ISSUE THREAD

**Issue by drnic** [buildkite/cli#78]
What is `bk`'s relationship with https://github.com/buildkite/emojis?

In the example pipeline below, only `:thumbsup:` is supported by `bk`:

```yaml
steps:
  - command: "sleep 2"
    label: ":thumbsup:"
  - command: "sleep 2"
    label: ":thumbsup::skin-tone-2:"
  - command: "sleep 2"
    label: ":+1:"
  - command: "sleep 2"
    label: ":+1::skin-tone-2:"
```

The output includes:

```
>>> Executing command step 👍
...
>>> Executing command step 👍:skin-tone-2:
...
>>> Executing command step :+1:
...
>>> Executing command step :+1::skin-tone-2:
```
