### ISSUE TITLE
bk local run - support if conditions - currently ignoring them

### ISSUE THREAD

**Issue by drnic** [buildkite/cli#79]
https://buildkite.com/docs/pipelines/conditionals

```yaml
steps:
  - command: "echo --- All good. Nice one."
    label: ":git:"
    if: build.branch == 'master'
  - command: "echo --- ERROR this shouldn't run; exit 1"
    label: ":git:"
    if: build.branch != 'master'
```

When I run this pipeline.yml it runs both steps; but it should only run one or the other.

@keithpitt is this something that should work, or one of those "its annoying to implement everything in ruby + golang" (my words not yours) gaps ;)

**Comment by gustavderdrache** [comment]
One follow-on issue with this is that `bk run` doesn't reject this invalid step definition, which tripped me up when I was trying to use it to double-check that I had my conditionals right:

```yaml
steps:
   - label: Test PRs
     command: echo hello
     branches: "!main"
     if: build.pull_request.id != null
```
