### ISSUE TITLE
`bk local run` doesn't respect skip

### ISSUE THREAD

**Issue by jack1902** [buildkite/cli#80]
### Description

Currently, when running `bk local run` with a step containing `skip: true` the agent still runs the commands 

### Steps to reproduce

* Create a basic pipeline with the below under `.buildkite/pipeline.yml`:

```yaml
steps:
  - label: ":coffee: i need coffee :coffee:"
    skip: true
    commands:
      - echo "coffee is better than tea" > file.out

  - wait

  - label: ":hammer: file.out is created"
    commands:
      - echo "There shouldn't be a file.out but there is :("
```

* Run `bk local run` and observe the creation of the `file.out` which shouldn't exist as it should be skipped

## Desired Outcome

The key `skip` is respected, with its `bool` value or `string`
